sudo: true
services: docker
language: python
python:
  - 3.6
  - 2.7

install: |
  shopt -s expand_aliases
  docker pull omercnet/tox:alpine
  alias tox='docker run --rm -it --env-file <(env | egrep "TRAVIS|CI") -v `pwd`:/app -v /var/run/docker.sock:/var/run/docker.sock omercnet/tox:alpine tox'

script: tox

stages:
  - lint
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: lint
      script: tox -e flake8
      deploy:
    - stage: deploy
      install: skip
      script: ./mkpkg.sh
      deploy:
        provider: pages
        skip_cleanup: true
        keep-history: true
        github-token: $GITHUB_TOKEN
        local-dir: dist/
        on:
          branch: master
