sudo: false

install: skip
script: ./mkpkg.sh

deploy:
  provider: pages
  script: skip
  skip_cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  on:
    branch: master
